/* DO NOT EDIT THIS FILE - it is machine generated */
#include "speex_native.h"
#include "include/speex/speex_echo.h"
#include "include/speex/speex_preprocess.h"

#define TAG "LibSpeex" // 这个是自定义的LOG的标识
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG,TAG ,__VA_ARGS__) // 定义LOGD类型
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,TAG ,__VA_ARGS__) // 定义LOGI类型
#define LOGW(...) __android_log_print(ANDROID_LOG_WARN,TAG ,__VA_ARGS__) // 定义LOGW类型
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR,TAG ,__VA_ARGS__) // 定义LOGE类型
#define LOGF(...) __android_log_print(ANDROID_LOG_FATAL,TAG ,__VA_ARGS__) // 定义LOGF类型

/*
 * Class:     com_example_libspeex_SpeexNative
 * Method:    nativeInit
 * Signature: (III)I
 */

 int nInitSuccessFlag = -1;
 int nInitDeNoseFlag = -1;

 SpeexEchoState* m_pState = NULL;
 SpeexPreprocessState* m_pPreprocessorState = NULL;

 SpeexPreprocessState* audioProcNose8K = NULL;
 SpeexPreprocessState* audioProcNose16K = NULL;

JNIEXPORT jint JNICALL Java_com_example_libspeex_SpeexNative_nativeInitEcho
  (JNIEnv* env,jobject thiz,jint frame_size,jint filter_length,jint sampling_rate){
  if(nInitSuccessFlag == 1)
  return 0 ;

  int m_nFrameSize  = frame_size;
  int m_nFilterLen  = filter_length;
  int m_nSampleRate = sampling_rate;

  //计算采样时长，即是10毫秒，还是20毫秒，还是30毫秒
  int nSampleTimeLong = (frame_size / (sampling_rate / 100)) * 10 ;

  SpeexEchoState* m_pState = speex_echo_state_init(m_nFrameSize, m_nFilterLen);
  if(m_pState == NULL)
  return -1 ;

  m_pPreprocessorState = speex_preprocess_state_init(m_nFrameSize, m_nSampleRate);
  if(m_pPreprocessorState == NULL)
  return -2 ;

  int iArg = m_nSampleRate;
  speex_echo_ctl(m_pState, SPEEX_ECHO_SET_SAMPLING_RATE, &iArg);
  speex_preprocess_ctl(m_pPreprocessorState, SPEEX_PREPROCESS_SET_ECHO_STATE, m_pState);

   nInitSuccessFlag = 1 ;

   return 0 ;
  }

  /*
   * Class:     com_example_libspeex_SpeexNative
   * Method:    nativeProc
   * Signature: ([B[B[B)I
   */
  JNIEXPORT jint JNICALL Java_com_example_libspeex_SpeexNative_nativeProcEcho
    (JNIEnv* env,jobject thiz,jbyteArray recordArray,jbyteArray playArray,jbyteArray szOutArray){
    if(nInitSuccessFlag == 0)
    return -1;

     LOGE("break--1");
     jbyte* recordBuffer = (jbyte *)(*env)->GetByteArrayElements(env,recordArray, 0);
     jbyte* playBuffer = (jbyte *)(*env)->GetByteArrayElements(env,playArray, 0);
     jbyte* szOutBuffer = (jbyte *)(*env)->GetByteArrayElements(env,szOutArray, 0);

     LOGE("break--2");

    speex_echo_cancellation(m_pState,(spx_int16_t *)recordBuffer,
          (spx_int16_t *)playBuffer,(spx_int16_t *)szOutBuffer);
           LOGE("break--2.5");
    int flag=speex_preprocess_run(m_pPreprocessorState,(spx_int16_t *)szOutBuffer);

LOGE("break--3");
     (*env)->ReleaseByteArrayElements(env,recordArray,recordBuffer,0) ;
     (*env)->ReleaseByteArrayElements(env,playArray,playBuffer,0) ;
     (*env)->ReleaseByteArrayElements(env,szOutArray,szOutBuffer,0) ;
LOGE("break--4");
     return 0 ;
    }

/*
 * Class:     com_example_libspeex_SpeexNative
 * Method:    nativeClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_libspeex_SpeexNative_nativeCloseEcho
  (JNIEnv* env,jobject thiz){
  if(nInitSuccessFlag == 0)
  return -1 ;

  if (m_pState != NULL)
  {
  speex_echo_state_destroy(m_pState);
  m_pState = NULL;
  }
  if (m_pPreprocessorState != NULL)
  {
  speex_preprocess_state_destroy(m_pPreprocessorState);
  m_pPreprocessorState = NULL;
  }

   nInitSuccessFlag = 0 ;

   return 0 ;
  }




  /*
   * Class:     com_example_libspeex_SpeexNative
   * Method:    nativeInitDeNose
   * Signature: (III)I
   */
  JNIEXPORT jint JNICALL Java_com_example_libspeex_SpeexNative_nativeInitDeNose
    (JNIEnv* env,jobject thiz,jint frame_size,jint filter_length,jint sampling_rate) {
    int denoise_enabled = 1 ;
    if(nInitDeNoseFlag == 1)
    return 0 ;

     nInitDeNoseFlag = 1 ;

     int m_nFrameSize  = frame_size;
     int m_nFilterLen  = filter_length;
     int m_nSampleRate = sampling_rate;

     //计算采样时长，即是10毫秒，还是20毫秒，还是30毫秒
     int nSampleTimeLong = (frame_size / (sampling_rate / 100)) * 10 ;

     //8K降噪
    audioProcNose8K = speex_preprocess_state_init(80 * (nSampleTimeLong / 10),8000);
    speex_preprocess_ctl(audioProcNose8K, SPEEX_PREPROCESS_SET_DENOISE, &denoise_enabled);

    //16K降噪
    audioProcNose16K = speex_preprocess_state_init(160 * (nSampleTimeLong / 10),16000);
    speex_preprocess_ctl(audioProcNose16K, SPEEX_PREPROCESS_SET_DENOISE, &denoise_enabled);

     return 0;
    }

    /*
     * Class:     com_example_libspeex_SpeexNative
     * Method:    nativeProcDeNose8K
     * Signature: ([B)I
     */
   JNIEXPORT jint JNICALL Java_com_example_libspeex_SpeexNative_nativeProcDeNose8K
      (JNIEnv* env,jobject thiz,jbyteArray recordArray) {
      if(nInitDeNoseFlag == 0)
      return -1 ;

        jbyte* recordBuffer = (jbyte *)(*env)->GetByteArrayElements(env,recordArray, 0);

        speex_preprocess(audioProcNose8K,(spx_int16_t*)recordBuffer, NULL);

       (*env)->ReleaseByteArrayElements(env,recordArray,recordBuffer,0) ;

       return 0 ;
      }

    /*
     * Class:     com_example_libspeex_SpeexNative
     * Method:    nativeProcDeNose16K
     * Signature: ([B)I
     */
    JNIEXPORT jint JNICALL Java_com_example_libspeex_SpeexNative_nativeProcDeNose16K
      (JNIEnv* env,jobject thiz,jbyteArray recordArray) {
      if(nInitDeNoseFlag == 0)
      return -1 ;

        jbyte* recordBuffer = (jbyte *)(*env)->GetByteArrayElements(env,recordArray, 0);

        speex_preprocess(audioProcNose16K,(spx_int16_t*)recordBuffer, NULL);

       (*env)->ReleaseByteArrayElements(env,recordArray,recordBuffer,0) ;

       return 0 ;
    }

   /*
    * Class:     com_example_libspeex_SpeexNative
    * Method:    nativeCloseDeNose
    * Signature: ()I
    */
   JNIEXPORT jint JNICALL Java_com_example_libspeex_SpeexNative_nativeCloseDeNose
     (JNIEnv* env,jobject thiz) {
     if(nInitDeNoseFlag == 0)
     return -1 ;

      nInitDeNoseFlag = 0 ;

     speex_preprocess_state_destroy(audioProcNose8K);
     speex_preprocess_state_destroy(audioProcNose16K);

      return 0 ;
     }